import os
import sys


Import('env')

# env["CC"] = os.getenv("CC") or env["CC"]
# env["CXX"] = os.getenv("CXX") or env["CXX"]
# env["ENV"].update(x for x in os.environ.items() if x[0].startswith("C"))


def dump_list(name):
    xlist = env[name]
    # print("dump " + name)
    for var in xlist:
        var = var
        # print("-- " + str(var))


env.ParseConfig('echo -I../.xopt/include/')
dump_list('CPPPATH')
dump_list('LIBS')

env.ParseConfig('echo ../.xopt/lib/liblogger.a')
dump_list('LIBS')
env.Program(target='../build/fs_raii-test', source='fs_raii-test.c')
