import os
import sys


Import('env')

# env["CC"] = os.getenv("CC") or env["CC"]
# env["CXX"] = os.getenv("CXX") or env["CXX"]
# env["ENV"].update(x for x in os.environ.items() if x[0].startswith("C"))


def dump_list(name):
    xlist = env[name]
    # print("dump " + name)
    for var in xlist:
        var = var
        # print("-- " + str(var))


topdir=Dir('#').abspath
# env.ParseConfig('echo -I' + topdir + "/.xopt/include")

env.StaticLibrary(target=topdir + '/build/core', source='osclock.c')
